activation: silu
aggregation_method: sum
anchors_context: false
attention: false
batch_size: 64
center_of_mass: fragments
context_node_nf: 1
data_augmentation: false
data_path: ../argonne_gnn_gitlab/DiffLinker/data/geom/datasets
diffusion_loss_type: l2
diffusion_noise_precision: 1.0e-05
diffusion_noise_schedule: polynomial_2
diffusion_steps: 500
hidden_nf: 128
in_node_nf: 9
include_charges: false
inpainting: false
inv_sublayers: 2
log_iterations: null
lr: 0.0002
model: egnn_dynamics
n_dims: 3
n_layers: 6
n_stability_samples: 10
norm_constant: 1.0e-06
normalization: batch_norm
normalization_factor: 100
normalize_factors:
- 1
- 4
- 10
samples_dir: logs/samples/config_hyunpark_geom_difflinker_bs64_date03-10_time12-21-07.320337
sin_embedding: false
tanh: false
test_epochs: 1
torch_device: cuda:0
train_data_prefix: geom_multifrag_train
val_data_prefix: geom_multifrag_val
